# syntax=docker/dockerfile:1

FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=/api
ARG VITE_GOOGLE_STUDENT_ENTRY_URL=
ARG VITE_GOOGLE_STUDENT_THCS_ENTRY_URL=
ARG VITE_GOOGLE_STUDENT_THPT_ENTRY_URL=
ARG VITE_GOOGLE_COUNSELOR_ENTRY_URL=
ARG VITE_STUDENT_SYNC_INTERVAL_MS=10000

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_GOOGLE_STUDENT_ENTRY_URL=$VITE_GOOGLE_STUDENT_ENTRY_URL \
    VITE_GOOGLE_STUDENT_THCS_ENTRY_URL=$VITE_GOOGLE_STUDENT_THCS_ENTRY_URL \
    VITE_GOOGLE_STUDENT_THPT_ENTRY_URL=$VITE_GOOGLE_STUDENT_THPT_ENTRY_URL \
    VITE_GOOGLE_COUNSELOR_ENTRY_URL=$VITE_GOOGLE_COUNSELOR_ENTRY_URL \
    VITE_STUDENT_SYNC_INTERVAL_MS=$VITE_STUDENT_SYNC_INTERVAL_MS \
    VITE_CRUD_DEMO_MODE=false

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1/ || exit 1

